[package]
name = "adobergb"
version = "0.0.0"
edition = "2021"

[dependencies]
anstream = "0.6.17"
num = "0.4"

[profile.release]
debug = false
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
